Document: livestreamer
Title: Debian livestreamer Manual
Author: <insert document author here>
Abstract: This manual describes what livestreamer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/livestreamer/livestreamer.sgml.gz

Format: postscript
Files: /usr/share/doc/livestreamer/livestreamer.ps.gz

Format: text
Files: /usr/share/doc/livestreamer/livestreamer.text.gz

Format: HTML
Index: /usr/share/doc/livestreamer/html/index.html
Files: /usr/share/doc/livestreamer/html/*.html
